//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCVStockTool.Language.ProductItem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FCVStockTool.Language.ProductItem.ProItem", typeof(ProItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddProItem {
            get {
                return ResourceManager.GetString("AddProItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD ROM.
        /// </summary>
        public static string CDROM {
            get {
                return ResourceManager.GetString("CDROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a building.
        /// </summary>
        public static string ChooseBuilding {
            get {
                return ResourceManager.GetString("ChooseBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Department.
        /// </summary>
        public static string ChooseDepartment {
            get {
                return ResourceManager.GetString("ChooseDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select an employee.
        /// </summary>
        public static string ChooseEmployee {
            get {
                return ResourceManager.GetString("ChooseEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Product.
        /// </summary>
        public static string ChoosePro {
            get {
                return ResourceManager.GetString("ChoosePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Status Product.
        /// </summary>
        public static string ChooseStatusPro {
            get {
                return ResourceManager.GetString("ChooseStatusPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Status Warehouse.
        /// </summary>
        public static string ChooseStatusWare {
            get {
                return ResourceManager.GetString("ChooseStatusWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreatePro {
            get {
                return ResourceManager.GetString("CreatePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Buy (mm/dd/yyyy).
        /// </summary>
        public static string DateBuy {
            get {
                return ResourceManager.GetString("DateBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteProItem {
            get {
                return ResourceManager.GetString("DeleteProItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept: .
        /// </summary>
        public static string Dept {
            get {
                return ResourceManager.GetString("Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditPro {
            get {
                return ResourceManager.GetString("EditPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Detail.
        /// </summary>
        public static string InforDetail {
            get {
                return ResourceManager.GetString("InforDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of devices.
        /// </summary>
        public static string ListPro {
            get {
                return ResourceManager.GetString("ListPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng điền tên thiết bị.
        /// </summary>
        public static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Order.
        /// </summary>
        public static string NumberOrder {
            get {
                return ResourceManager.GetString("NumberOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Date.
        /// </summary>
        public static string PODate {
            get {
                return ResourceManager.GetString("PODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset code.
        /// </summary>
        public static string PONo {
            get {
                return ResourceManager.GetString("PONo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose product..
        /// </summary>
        public static string ProductError {
            get {
                return ResourceManager.GetString("ProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tình trạng thiết bị.
        /// </summary>
        public static string ProductStatusError {
            get {
                return ResourceManager.GetString("ProductStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please  enter serial from 1 to 100 letter..
        /// </summary>
        public static string SerialErrorLenght {
            get {
                return ResourceManager.GetString("SerialErrorLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number serial..
        /// </summary>
        public static string SerialNoError {
            get {
                return ResourceManager.GetString("SerialNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Code.
        /// </summary>
        public static string ShortCode {
            get {
                return ResourceManager.GetString("ShortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập shortcode..
        /// </summary>
        public static string ShortCodeError {
            get {
                return ResourceManager.GetString("ShortCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Product.
        /// </summary>
        public static string StatusPro {
            get {
                return ResourceManager.GetString("StatusPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Warehouse.
        /// </summary>
        public static string StatusWarehouse {
            get {
                return ResourceManager.GetString("StatusWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tình trạng kho.
        /// </summary>
        public static string StockStatusError {
            get {
                return ResourceManager.GetString("StockStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Unitprice {
            get {
                return ResourceManager.GetString("Unitprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateProItem {
            get {
                return ResourceManager.GetString("UpdateProItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses history.
        /// </summary>
        public static string Warehouseshistory {
            get {
                return ResourceManager.GetString("Warehouseshistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty (month).
        /// </summary>
        public static string Warranty {
            get {
                return ResourceManager.GetString("Warranty", resourceCulture);
            }
        }
    }
}
